{
 "title": "fail2ban - attacks",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total IPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \ncount(country),time\nfrom ips\n"
    }
   ]
  },
  {
   "title": "ISPs",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  country,\n  count(isp) as \"isp_count\"\nFROM ips.ips\ngroup by country,isp\norder by isp_count desc"
    }
   ]
  },
  {
   "title": "Attacks per city",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lat,\n  lng,\n  city,\n  count(city) as cities,\n  ip as metric\nFROM ips\nWHERE\n  $__timeFilter(time)\ngroup by city"
    }
   ]
  },
  {
   "title": "Attacks per region",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 15 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lat,\n  lng,\n  city,\n  count(city) as \"cities\",\n  ip as \"metric\"\nFROM ips.ips\nWHERE\n  $__timeFilter(time)\ngroup by city"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  city,\n  count(city) as \"metrica\"\n  \nFROM ips.ips \ngroup by city"
    }
   ]
  },
  {
   "title": "Attacks per country",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 15 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  avg(lat) as \"lat\",\n  avg(lng) as \"lng\",\n  country,\n  count(country) as \"countries\",\n  ip as \"metric\"\nFROM ips\nWHERE\n  $__timeFilter(time)\ngroup by country"
    }
   ]
  }
 ]
}