version: "3.9"
services:
  grafana:
    links:
      - mysql-db:mysql-db
    image: grafana/grafana:latest
    volumes:
      - ./grafana:/var/lib/grafana:rw
      # - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_DATABASE_HOST=mysql-db:3306
      - GF_DATABASE_NAME=grafanadb
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=test1234
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_MAX_OPEN_CONN=300
    ports:
      - "127.0.0.1:3000:3000"
    depends_on: ["mysql-db"]
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: grafanadb
      MYSQL_USER: grafana
      MYSQL_PASSWORD: test1234
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb_monitor_enable=all,
        --max-connections=1001,
      ]
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d//init.sql
    ports:
      - "127.0.0.1:3306:3006"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10